//! Devin Session authentication service
//!
//! Implements new authentication system based on Devin Session, including:
//! - `POST /_devin-auth/connections` — query available login methods for email
//! - `POST /_devin-auth/password/login` — account password login, returns auth1_token
//! - `SeatManagementService/WindsurfPostAuth` — exchange auth1_token for session_token
//!
//! Design points:
//! - Full same-origin requests (windsurf.com), no Google API Key involved, so no special Referer handling needed
//! - All REST requests include `Origin: https://windsurf.com` and `Referer: https://windsurf.com/account/login`
//!   to maintain consistency with browser behavior and avoid certain edge CSP rejections

use crate::utils::{AppError, AppResult};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

/// Base URL for Devin password login (via windsurf.com same-origin proxy)
const DEVIN_AUTH_BASE_URL: &str = "https://windsurf.com/_devin-auth";
/// WindsurfPostAuth goes to main backend
const WINDSURF_BACKEND_URL: &str = "https://web-backend.windsurf.com";

// ==================== Request/Response Structures ===

#[derive(Debug, Serialize)]
pub struct ConnectionsRequest {
    pub product: String,
    pub email: String,
}

/// Response for `/_devin-auth/connections` (structure inferred from observation, unknown fields will be ignored)
#[derive(Debug, Deserialize, Serialize, Default)]
#[serde(default)]
pub struct ConnectionsResponse {
    /// List of available connection methods (raw JSON passthrough to tolerate field changes)
    #[serde(flatten)]
    pub raw: serde_json::Value,
}

#[derive(Debug, Serialize)]
pub struct PasswordLoginRequest {
    pub email: String,
    pub password: String,
}

/// Response for `/_devin-auth/password/login`
///
/// Actual response body example from testing:
/// ```json
/// {
///   "token": "auth1_yjk627jgorikbvs5u5r5ubsjszuuugu6uwvbecarhidxhmntl4zq",
///   "user_id": "user-5b148c75b9cb4bf2b48e1ae73ee13277",
///   "email": "aporter755@fnsdghm.shop"
/// }
/// ```
///
/// Field aliases also compatible with early speculated names (`auth1_token` / `account_id`).
#[derive(Debug, Deserialize, Serialize)]
pub struct PasswordLoginResponse {
    /// Primary authentication token (format: `auth1_<52 random characters>`)
    ///
    /// Actual API returns field name `token`; here we keep `auth1_token` as the Rust-side main name,
    /// and use alias to be compatible with `token` / `auth1Token` / `auth_token`.
    #[serde(alias = "token", alias = "auth1Token", alias = "auth_token")]
    pub auth1_token: String,
    /// Devin account/user ID (actual returned field is `user_id`, format: `user-<32 characters>`)
    #[serde(default, alias = "user_id", alias = "userId", alias = "accountId")]
    pub account_id: Option<String>,
    /// Returned email (server will echo back for verification)
    #[serde(default)]
    pub email: Option<String>,
    /// Preserve unknown fields for debugging
    #[serde(flatten)]
    pub extra: serde_json::Value,
}

/// Parsed response structure for `WindsurfPostAuth`
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct WindsurfPostAuthResult {
    pub session_token: String,
    #[serde(default)]
    pub auth1_token: Option<String>,
    #[serde(default)]
    pub account_id: Option<String>,
    #[serde(default)]
    pub primary_org_id: Option<String>,
    #[serde(default)]
    pub orgs: Vec<WindsurfOrg>,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct WindsurfOrg {
    pub id: String,
    pub name: String,
}

/// Response parsing structure for `CheckUserLoginMethod`
///
/// Source: `exa.seat_management_pb.SeatManagementService/CheckUserLoginMethod`
///
/// Proto schema (field numbers restored from official website frontend chunk):
/// - 1: `redirect_url` (string)      — multi-region/security-wide redirect URL, empty means no redirect
/// - 2: `disallow_enterprise_user_login` (bool) — enterprise users prohibited from normal login
/// - 3: `user_exists` (bool)          — whether this email exists on WS(Firebase) side
/// - 4: `is_migrated` (bool)          — whether migrated to Auth1
/// - 5: `has_password` (bool)         — whether password credentials have been set
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct CheckUserLoginMethodResult {
    #[serde(default)]
    pub redirect_url: String,
    #[serde(default)]
    pub disallow_enterprise_user_login: bool,
    #[serde(default)]
    pub user_exists: bool,
    #[serde(default)]
    pub is_migrated: bool,
    #[serde(default)]
    pub has_password: bool,
}

/// Login method sniffing aggregation result
///
/// Generated by [`DevinAuthService::sniff_login_method`], aggregating detection data from both sides:
/// - Firebase(WS) side: `CheckUserLoginMethod`
/// - Devin side:  `/_devin-auth/connections`
///
/// `recommended` field values and meanings (aligned with official website reducer BOTH_CHECKS_DONE):
/// - `"firebase"`    — old Firebase account + password set, use `signInWithEmailAndPassword`
/// - `"devin"`       — migrated or new Auth1 account, use Devin password login
/// - `"sso"`         — connected enterprise SSO, must complete SSO redirect in browser
/// - `"no_password"` — old account only used Google/GitHub, need OAuth or reset password first
/// - `"not_found"`   — email doesn't exist on either side, suggest registration first
/// - `"blocked"`     — enterprise user restricted from normal login channel
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct LoginMethodSniffResult {
    /// Recommended login method
    pub recommended: String,
    /// Human-readable reason explanation (can be displayed directly to UI)
    pub reason: String,

    // ==== Firebase(WS) side original determination ===
    pub user_exists: bool,
    pub is_migrated: bool,
    pub has_password: bool,
    pub redirect_url: Option<String>,
    pub disallow_enterprise: bool,

    // ==== Devin side original determination ===
    /// Raw JSON returned by Devin `/connections`, `None` when interface fails/email doesn't exist
    pub devin_connections: Option<serde_json::Value>,
    /// Devin side `method` field: `"auth1"` | `"not_found"` | null
    pub devin_method: Option<String>,
    /// Devin side `has_password` field
    pub devin_has_password: Option<bool>,
    /// Whether Devin side `sso_connections` array is non-empty
    pub has_sso_connection: bool,
}

/// Final result of complete login flow
#[derive(Debug, Serialize, Clone)]
pub struct DevinLoginResult {
    pub session_token: String,
    pub auth1_token: String,
    pub account_id: Option<String>,
    pub primary_org_id: Option<String>,
    pub orgs: Vec<WindsurfOrg>,
    /// When multiple organizations are returned, user needs to make a second selection and call windsurf_post_auth(auth1_token, chosen_org_id)
    pub requires_org_selection: bool,
}

// ==================== Email Registration / Passwordless Login / Forgot Password Related Structures ===

/// Request for `/email/start`
#[derive(Debug, Serialize)]
pub struct EmailStartRequest {
    pub email: String,
    /// `"signup"` | `"login"`
    pub mode: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product: Option<String>,
}

/// Response for `/email/start` and `/password/reset-start` (both have consistent structure)
///
/// Server will send a 6-digit verification code to `email` and return `email_verification_token`,
/// which the frontend passes back in subsequent `/email/complete` or `/password/reset-complete` steps.
#[derive(Debug, Deserialize, Serialize, Clone, Default)]
pub struct EmailStartResponse {
    #[serde(default)]
    pub email_verification_token: String,
    /// Other fields (such as `expires_at`, `max_attempts`, etc.) are passed through as fallback for debugging
    #[serde(flatten)]
    pub extra: serde_json::Value,
}

/// Request for `/email/complete`
#[derive(Debug, Serialize)]
pub struct EmailCompleteRequest {
    pub email_verification_token: String,
    pub code: String,
    /// `"signup"`: registration; `"login"`: passwordless email login
    pub mode: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Request for `/password/reset-start`
#[derive(Debug, Serialize)]
pub struct PasswordResetStartRequest {
    pub email: String,
    pub product: String,
}

/// Request for `/password/reset-complete`
#[derive(Debug, Serialize)]
pub struct PasswordResetCompleteRequest {
    pub email_verification_token: String,
    pub code: String,
    pub new_password: String,
}

// ==================== Service Implementation ===

pub struct DevinAuthService {
    client: Arc<reqwest::Client>,
}

impl DevinAuthService {
    pub fn new() -> Self {
        // Devin Auth goes via windsurf.com same-origin proxy, **does not** go through Google API Client
        // So here we use the global normal HTTP Client (supports user agent configuration but no Google restrictions)
        Self {
            client: super::get_http_client(),
        }
    }

    /// Attach common headers to all REST requests (simulate browser behavior)
    fn apply_common_headers(builder: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        builder
            .header("Content-Type", "application/json")
            .header("Accept", "*/*")
            .header("Accept-Language", "zh-CN,zh;q=0.9")
            .header("Origin", "https://windsurf.com")
            .header("Referer", "https://windsurf.com/account/login")
            .header("Sec-Fetch-Dest", "empty")
            .header("Sec-Fetch-Mode", "cors")
            .header("Sec-Fetch-Site", "same-origin")
            .header(
                "User-Agent",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
                 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
            )
    }

    /// Query available connection methods for email (optional step, for UI pre-judgment)
    pub async fn check_connections(&self, email: &str) -> AppResult<ConnectionsResponse> {
        let url = format!("{}/connections", DEVIN_AUTH_BASE_URL);

        let body = ConnectionsRequest {
            product: "windsurf".to_string(),
            email: email.to_string(),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin connections request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response.text().await.map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(AppError::Api(format!(
                "Devin connections returned status {}: {}",
                status, text
            )));
        }

        let parsed: ConnectionsResponse = serde_json::from_str(&text)
            .unwrap_or_else(|_| ConnectionsResponse::default());

        Ok(parsed)
    }

    /// Login with email password, returns `auth1_token`
    pub async fn password_login(
        &self,
        email: &str,
        password: &str,
    ) -> AppResult<PasswordLoginResponse> {
        let url = format!("{}/password/login", DEVIN_AUTH_BASE_URL);

        let body = PasswordLoginRequest {
            email: email.to_string(),
            password: password.to_string(),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin login request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response.text().await.map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(Self::parse_password_login_error(status.as_u16(), &text));
        }

        serde_json::from_str::<PasswordLoginResponse>(&text).map_err(|e| {
            AppError::Parse(format!(
                "Failed to parse Devin login response: {}. Body: {}",
                e, text
            ))
        })
    }

    /// Translate common error responses to user-readable information
    fn parse_password_login_error(status: u16, body: &str) -> AppError {
        let lower = body.to_lowercase();
        if lower.contains("invalid") && (lower.contains("password") || lower.contains("credentials"))
        {
            AppError::AuthFailed("Invalid email or password".to_string())
        } else if lower.contains("not found") || lower.contains("no such") {
            AppError::AuthFailed("This email is not registered with a Devin account".to_string())
        } else if lower.contains("disabled") || lower.contains("suspended") {
            AppError::AuthFailed("Account has been disabled or suspended".to_string())
        } else if lower.contains("verify") && lower.contains("email") {
            AppError::AuthFailed("Please verify your email first".to_string())
        } else if lower.contains("too many") || lower.contains("rate") || status == 429 {
            AppError::AuthFailed("Too many attempts, please try again later".to_string())
        } else {
            AppError::AuthFailed(format!("Devin login failed({}): {}", status, body))
        }
    }

    /// Exchange `auth1_token` (+ optional `org_id`) for final `session_token`
    ///
    /// Call SeatManagementService/WindsurfPostAuth via gRPC-Web (application/proto)
    pub async fn windsurf_post_auth(
        &self,
        auth1_token: &str,
        org_id: &str,
    ) -> AppResult<WindsurfPostAuthResult> {
        let url = format!(
            "{}/exa.seat_management_pb.SeatManagementService/WindsurfPostAuth",
            WINDSURF_BACKEND_URL
        );

        // Protobuf encoding: field 1 (auth1_token) + field 2 (org_id)
        let mut body = Vec::with_capacity(auth1_token.len() + org_id.len() + 4);
        encode_proto_string_field(&mut body, 1, auth1_token);
        if !org_id.is_empty() {
            encode_proto_string_field(&mut body, 2, org_id);
        }

        let response = self
            .client
            .post(&url)
            .body(body)
            .header("accept", "*/*")
            .header("accept-language", "zh-CN,zh;q=0.9")
            .header("connect-protocol-version", "1")
            .header("content-type", "application/proto")
            .header("origin", "https://windsurf.com")
            .header("referer", "https://windsurf.com/account/login")
            .header("sec-fetch-dest", "empty")
            .header("sec-fetch-mode", "cors")
            .header("sec-fetch-site", "same-site")
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("WindsurfPostAuth request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let bytes = response
            .bytes()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(AppError::Api(format!(
                "WindsurfPostAuth returned status {}: {}",
                status,
                String::from_utf8_lossy(&bytes)
            )));
        }

        parse_windsurf_post_auth_response(&bytes)
    }

    /// One-click complete login: connectivity check → password login → exchange session_token
    ///
    /// If returned orgs are more than 1 and caller didn't pre-specify `org_id`, the returned result
    /// will have `requires_org_selection = true`, requiring UI to make a second call to `windsurf_post_auth` with selected org_id
    pub async fn login_with_password(
        &self,
        email: &str,
        password: &str,
        org_id: Option<&str>,
    ) -> AppResult<DevinLoginResult> {
        // Step 1: Password login, get auth1_token
        let login = self.password_login(email, password).await?;
        // Step 2: Exchange auth1_token for session_token and construct DevinLoginResult
        self.post_auth_to_login_result(login, org_id).await
    }

    // ==================== Login Method Sniffing (Plan B Core) ===

    /// Anonymously call `CheckUserLoginMethod` to get Firebase(WS) side login method judgment for this email
    ///
    /// Endpoint: `POST https://web-backend.windsurf.com/exa.seat_management_pb.SeatManagementService/CheckUserLoginMethod`
    /// Protocol: Connect-Web protobuf (binary)
    /// Request body: field 1 = email (string)
    ///
    /// No auth token required, can query any email.
    pub async fn check_user_login_method(
        &self,
        email: &str,
    ) -> AppResult<CheckUserLoginMethodResult> {
        let url = format!(
            "{}/exa.seat_management_pb.SeatManagementService/CheckUserLoginMethod",
            WINDSURF_BACKEND_URL
        );

        let mut body = Vec::with_capacity(email.len() + 4);
        encode_proto_string_field(&mut body, 1, email);

        let response = self
            .client
            .post(&url)
            .body(body)
            .header("accept", "*/*")
            .header("accept-language", "zh-CN,zh;q=0.9")
            .header("connect-protocol-version", "1")
            .header("content-type", "application/proto")
            .header("origin", "https://windsurf.com")
            .header("referer", "https://windsurf.com/account/login")
            .header("sec-fetch-dest", "empty")
            .header("sec-fetch-mode", "cors")
            .header("sec-fetch-site", "same-site")
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("CheckUserLoginMethod request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let bytes = response
            .bytes()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(AppError::Api(format!(
                "CheckUserLoginMethod returned status {}: {}",
                status,
                String::from_utf8_lossy(&bytes)
            )));
        }

        parse_check_user_login_method_response(&bytes)
    }

    /// Aggregated sniffing: concurrently call Firebase `CheckUserLoginMethod` + Devin `/_devin-auth/connections`,
    /// give unified login method recommendation.
    ///
    /// Decision priority (fully aligned with official website reducer `BOTH_CHECKS_DONE`):
    /// 1. `disallow_enterprise_user_login == true` → `blocked`
    /// 2. Devin side `sso_connections[]` non-empty AND WS side `!is_migrated` → `sso`
    /// 3. WS `user_exists && !is_migrated`:
    ///    - `has_password` → `firebase`
    ///    - `!has_password` → `no_password`
    /// 4. Devin `method == "auth1"` OR WS `is_migrated` → `devin`
    /// 5. Neither side exists → `not_found`
    ///
    /// When Devin side is unavailable (network exception / 4xx), only judge based on Firebase side to ensure availability.
    pub async fn sniff_login_method(&self, email: &str) -> AppResult<LoginMethodSniffResult> {
        // Concurrent detection on both sides: Firebase side must succeed; Devin side allows failure
        let (ws_result, devin_result) =
            tokio::join!(self.check_user_login_method(email), self.check_connections(email));

        let ws = ws_result?;
        let connections = devin_result.ok();

        // Extract key fields from Devin connections response
        //
        // Official website frontend actually takes `connections.auth_method` sub-object (see official website chunk 1635:
        //   `let [e, n] = await Promise.all([et(r), Wk("windsurf", r)]);`
        //   `let o = n.auth_method ?? null;`
        //   `dispatch({ type: "BOTH_CHECKS_DONE", wsResult: e, devinResult: o })`
        // ). So the three fields `method` / `has_password` / `sso_connections` are all under the `auth_method`
        // sub-object. Early direct extraction from raw top level would cause Devin side to never be read → misjudged as `not_found`.
        //
        // Compatibility fallback: if backend new version flattens fields to top level, can also read them (auth_method first, then raw top level).
        let (devin_method, devin_has_password, has_sso_connection, devin_raw) = match &connections
        {
            Some(conn) => {
                let raw = &conn.raw;
                let auth_method = raw.get("auth_method");

                let read_str = |key: &str| {
                    auth_method
                        .and_then(|v| v.get(key))
                        .or_else(|| raw.get(key))
                        .and_then(|v| v.as_str())
                        .map(String::from)
                };
                let read_bool = |key: &str| {
                    auth_method
                        .and_then(|v| v.get(key))
                        .or_else(|| raw.get(key))
                        .and_then(|v| v.as_bool())
                };
                let read_array_non_empty = |key: &str| -> bool {
                    auth_method
                        .and_then(|v| v.get(key))
                        .or_else(|| raw.get(key))
                        .and_then(|v| v.as_array())
                        .map(|arr| !arr.is_empty())
                        .unwrap_or(false)
                };

                let method = read_str("method");
                let has_password = read_bool("has_password");
                let sso_present = read_array_non_empty("sso_connections");
                (method, has_password, sso_present, Some(raw.clone()))
            }
            None => (None, None, false, None),
        };

        let (recommended, reason): (&str, String) = if ws.disallow_enterprise_user_login {
            (
                "blocked",
                "Enterprise users are restricted from normal login, must use Devin Enterprise".to_string(),
            )
        } else if has_sso_connection && !ws.is_migrated {
            (
                "sso",
                "This email is bound to enterprise SSO, please complete SSO login in browser before importing".to_string(),
            )
        } else if ws.user_exists && !ws.is_migrated {
            if ws.has_password {
                (
                    "firebase",
                    "Old account has password set, use Firebase email password login".to_string(),
                )
            } else {
                (
                    "no_password",
                    "Old account has no password set (only Google/GitHub), please login with OAuth first or reset password"
                        .to_string(),
                )
            }
        } else if ws.is_migrated || devin_method.as_deref() == Some("auth1") {
            (
                "devin",
                "Migrated or new Auth1 account, use Devin password login".to_string(),
            )
        } else if !ws.user_exists
            && (devin_method.is_none() || devin_method.as_deref() == Some("not_found"))
        {
            (
                "not_found",
                "This email is not yet registered, please complete registration first".to_string(),
            )
        } else {
            (
                "not_found",
                "Cannot automatically determine login method, please manually select mode".to_string(),
            )
        };

        Ok(LoginMethodSniffResult {
            recommended: recommended.to_string(),
            reason,
            user_exists: ws.user_exists,
            is_migrated: ws.is_migrated,
            has_password: ws.has_password,
            redirect_url: if ws.redirect_url.is_empty() {
                None
            } else {
                Some(ws.redirect_url)
            },
            disallow_enterprise: ws.disallow_enterprise_user_login,
            devin_connections: devin_raw,
            devin_method,
            devin_has_password,
            has_sso_connection,
        })
    }

    // ==================== Email Registration / Passwordless Email Login / Forgot Password ===

    /// Send email verification code (reused for both registration / passwordless login, difference is in `mode`)
    ///
    /// - `mode == "signup"`: send verification code for new account creation
    /// - `mode == "login"`: send verification code for passwordless account email verification code login
    /// - `product`: default `Some("windsurf")` (case consistent with web side)
    ///
    /// Server will send a 6-digit verification code to target email and return `email_verification_token`,
    /// for subsequent `email_complete` callback use.
    pub async fn email_start(
        &self,
        email: &str,
        mode: &str,
        product: Option<&str>,
    ) -> AppResult<EmailStartResponse> {
        let url = format!("{}/email/start", DEVIN_AUTH_BASE_URL);

        let body = EmailStartRequest {
            email: email.to_string(),
            mode: mode.to_string(),
            product: product.map(|s| s.to_string()),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin email/start request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response
            .text()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(Self::parse_email_start_error(status.as_u16(), &text));
        }

        serde_json::from_str::<EmailStartResponse>(&text).map_err(|e| {
            AppError::Parse(format!(
                "Failed to parse Devin email/start response: {}. Body: {}",
                e, text
            ))
        })
    }

    /// Submit verification code + optional credentials to complete email flow
    ///
    /// - `mode == "signup"`: **must pass** `password` + `name`, success creates new Devin account
    /// - `mode == "login"`: **no need** for `password` / `name`, used for passwordless account email verification code login
    ///
    /// Successful response body structure consistent with `/password/login`: `{ token (auth1_token), user_id, email }`
    pub async fn email_complete(
        &self,
        email_verification_token: &str,
        code: &str,
        mode: &str,
        password: Option<&str>,
        name: Option<&str>,
    ) -> AppResult<PasswordLoginResponse> {
        let url = format!("{}/email/complete", DEVIN_AUTH_BASE_URL);

        let body = EmailCompleteRequest {
            email_verification_token: email_verification_token.to_string(),
            code: code.to_string(),
            mode: mode.to_string(),
            password: password.map(|s| s.to_string()),
            name: name.map(|s| s.to_string()),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin email/complete request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response
            .text()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(Self::parse_email_complete_error(status.as_u16(), &text));
        }

        serde_json::from_str::<PasswordLoginResponse>(&text).map_err(|e| {
            AppError::Parse(format!(
                "Failed to parse Devin email/complete response: {}. Body: {}",
                e, text
            ))
        })
    }

    /// Initiate "forgot password" flow: server sends reset verification code to `email`
    ///
    /// Response body structure consistent with `/email/start`: returns `email_verification_token`.
    /// Some server implementations may return empty body (only HTTP 200 indicates success), in which case returns response body with empty token,
    /// caller perceives and handles through errors in subsequent `password_reset_complete` (such as "invalid token").
    pub async fn password_reset_start(
        &self,
        email: &str,
        product: Option<&str>,
    ) -> AppResult<EmailStartResponse> {
        let url = format!("{}/password/reset-start", DEVIN_AUTH_BASE_URL);

        let body = PasswordResetStartRequest {
            email: email.to_string(),
            product: product.unwrap_or("Windsurf").to_string(),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin password/reset-start request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response
            .text()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(Self::parse_reset_error(status.as_u16(), &text));
        }

        if text.trim().is_empty() {
            return Ok(EmailStartResponse::default());
        }

        serde_json::from_str::<EmailStartResponse>(&text).map_err(|e| {
            AppError::Parse(format!(
                "Failed to parse Devin password/reset-start response: {}. Body: {}",
                e, text
            ))
        })
    }

    /// Complete "forgot password" flow: submit verification code + new password
    pub async fn password_reset_complete(
        &self,
        email_verification_token: &str,
        code: &str,
        new_password: &str,
    ) -> AppResult<()> {
        let url = format!("{}/password/reset-complete", DEVIN_AUTH_BASE_URL);

        let body = PasswordResetCompleteRequest {
            email_verification_token: email_verification_token.to_string(),
            code: code.to_string(),
            new_password: new_password.to_string(),
        };

        let response = Self::apply_common_headers(self.client.post(&url))
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                super::report_request_failure();
                AppError::Network(format!("Devin password/reset-complete request failed: {}", e))
            })?;

        super::report_request_success();

        let status = response.status();
        let text = response
            .text()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        if !status.is_success() {
            return Err(Self::parse_reset_error(status.as_u16(), &text));
        }

        Ok(())
    }

    /// Registration flow combination: `/email/complete`(signup) → `WindsurfPostAuth` → `DevinLoginResult`
    ///
    /// Prerequisite: caller has already obtained `email_verification_token` through `email_start(email, "signup", ...)`,
    /// and guided user to read verification code `code` in email.
    pub async fn register_with_email_code(
        &self,
        email_verification_token: &str,
        code: &str,
        password: &str,
        name: &str,
        org_id: Option<&str>,
    ) -> AppResult<DevinLoginResult> {
        let complete = self
            .email_complete(
                email_verification_token,
                code,
                "signup",
                Some(password),
                Some(name),
            )
            .await?;
        self.post_auth_to_login_result(complete, org_id).await
    }

    /// Passwordless email login flow combination: `/email/complete`(login) → `WindsurfPostAuth` → `DevinLoginResult`
    pub async fn login_with_email_code(
        &self,
        email_verification_token: &str,
        code: &str,
        org_id: Option<&str>,
    ) -> AppResult<DevinLoginResult> {
        let complete = self
            .email_complete(email_verification_token, code, "login", None, None)
            .await?;
        self.post_auth_to_login_result(complete, org_id).await
    }

    // ==================== Internal Shared ===

    /// After obtaining `PasswordLoginResponse` (i.e., response containing `auth1_token`),
    /// exchange for session_token and construct `DevinLoginResult`.
    ///
    /// Shared by `login_with_password` / `register_with_email_code` / `login_with_email_code`,
    /// avoiding duplicate implementation of auth1→session_token merge logic.
    async fn post_auth_to_login_result(
        &self,
        login: PasswordLoginResponse,
        org_id: Option<&str>,
    ) -> AppResult<DevinLoginResult> {
        let post_auth = self
            .windsurf_post_auth(&login.auth1_token, org_id.unwrap_or(""))
            .await?;

        let final_auth1_token = post_auth
            .auth1_token
            .clone()
            .unwrap_or_else(|| login.auth1_token.clone());
        let final_account_id = post_auth.account_id.clone().or(login.account_id.clone());
        let requires_org_selection = org_id.is_none() && post_auth.orgs.len() > 1;

        Ok(DevinLoginResult {
            session_token: post_auth.session_token,
            auth1_token: final_auth1_token,
            account_id: final_account_id,
            primary_org_id: post_auth.primary_org_id,
            orgs: post_auth.orgs,
            requires_org_selection,
        })
    }

    // ==================== Error Translation ===

    /// `/email/start` error translation
    fn parse_email_start_error(status: u16, body: &str) -> AppError {
        let lower = body.to_lowercase();
        if lower.contains("already") && lower.contains("exist") {
            AppError::AuthFailed("This email is already registered, please login directly".to_string())
        } else if lower.contains("invalid") && lower.contains("email") {
            AppError::AuthFailed("Invalid email format".to_string())
        } else if lower.contains("disposable") || lower.contains("temporary") {
            AppError::AuthFailed("Temporary / disposable email addresses are not supported".to_string())
        } else if lower.contains("too many") || lower.contains("rate") || status == 429 {
            AppError::AuthFailed("Verification code sent too frequently, please try again later".to_string())
        } else {
            AppError::AuthFailed(format!("Devin failed to send verification code({}): {}", status, body))
        }
    }

    /// `/email/complete` error translation
    fn parse_email_complete_error(status: u16, body: &str) -> AppError {
        let lower = body.to_lowercase();
        if lower.contains("invalid") && lower.contains("code") {
            AppError::AuthFailed("Invalid verification code".to_string())
        } else if lower.contains("expired") {
            AppError::AuthFailed("Verification code has expired, please request a new one".to_string())
        } else if lower.contains("password")
            && (lower.contains("weak") || lower.contains("short") || lower.contains("strength"))
        {
            AppError::AuthFailed("Password strength is insufficient".to_string())
        } else if lower.contains("already") && lower.contains("exist") {
            AppError::AuthFailed("This email is already registered".to_string())
        } else if lower.contains("too many") || lower.contains("rate") || status == 429 {
            AppError::AuthFailed("Too many attempts, please try again later".to_string())
        } else {
            AppError::AuthFailed(format!("Devin verification code submission failed({}): {}", status, body))
        }
    }

    /// `/password/reset-*` error translation
    fn parse_reset_error(status: u16, body: &str) -> AppError {
        let lower = body.to_lowercase();
        if lower.contains("invalid") && lower.contains("code") {
            AppError::AuthFailed("Invalid verification code".to_string())
        } else if lower.contains("expired") {
            AppError::AuthFailed("Verification code has expired, please request a new one".to_string())
        } else if lower.contains("not found") || lower.contains("no such") {
            AppError::AuthFailed("This email is not registered".to_string())
        } else if lower.contains("too many") || lower.contains("rate") || status == 429 {
            AppError::AuthFailed("Operation too frequent, please try again later".to_string())
        } else {
            AppError::AuthFailed(format!("Devin password reset failed({}): {}", status, body))
        }
    }
}

impl Default for DevinAuthService {
    fn default() -> Self {
        Self::new()
    }
}

// ==================== Protobuf Encoding/Decoding (handwritten, zero dependency) ===

/// Append varint encoding to buffer
fn encode_varint(buf: &mut Vec<u8>, mut value: u64) {
    while value >= 0x80 {
        buf.push((value as u8 & 0x7F) | 0x80);
        value >>= 7;
    }
    buf.push(value as u8);
}

/// Encode protobuf `string` field (wire type 2 = length-delimited)
fn encode_proto_string_field(buf: &mut Vec<u8>, field_no: u32, value: &str) {
    let tag = (field_no << 3) | 2;
    encode_varint(buf, tag as u64);
    let bytes = value.as_bytes();
    encode_varint(buf, bytes.len() as u64);
    buf.extend_from_slice(bytes);
}

/// Decode varint (returns value + consumed bytes)
fn decode_varint(bytes: &[u8], offset: usize) -> Option<(u64, usize)> {
    let mut result: u64 = 0;
    let mut shift = 0;
    let mut i = offset;
    while i < bytes.len() {
        let b = bytes[i];
        result |= ((b & 0x7F) as u64) << shift;
        i += 1;
        if b & 0x80 == 0 {
            return Some((result, i - offset));
        }
        shift += 7;
        if shift >= 64 {
            return None;
        }
    }
    None
}

/// Parse WindsurfPostAuthResponse
///
/// Proto structure:
/// - field 1: session_token (string)
/// - field 2: repeated WindsurfPostAuthOrg orgs (message)
///   - WindsurfPostAuthOrg.field 1: id (string)
///   - WindsurfPostAuthOrg.field 2: name (string)
/// - field 3: optional auth1_token (string)
/// - field 4: optional account_id (string)
/// - field 5: optional primary_org_id (string)
fn parse_windsurf_post_auth_response(bytes: &[u8]) -> AppResult<WindsurfPostAuthResult> {
    let mut result = WindsurfPostAuthResult::default();
    let mut i = 0;

    while i < bytes.len() {
        let (tag, consumed) = decode_varint(bytes, i).ok_or_else(|| {
            AppError::Parse("Failed to decode WindsurfPostAuth response tag varint".to_string())
        })?;
        i += consumed;

        let field_no = (tag >> 3) as u32;
        let wire_type = (tag & 0x7) as u8;

        // Only handle wire_type = 2 (length-delimited), skip other types by length
        if wire_type == 2 {
            let (len, consumed_len) = decode_varint(bytes, i).ok_or_else(|| {
                AppError::Parse("Failed to decode WindsurfPostAuth response length varint".to_string())
            })?;
            i += consumed_len;
            let end = i + len as usize;
            if end > bytes.len() {
                return Err(AppError::Parse(format!(
                    "WindsurfPostAuth response length out of bounds: field={} len={} i={} total={}",
                    field_no,
                    len,
                    i,
                    bytes.len()
                )));
            }
            let payload = &bytes[i..end];
            match field_no {
                1 => {
                    result.session_token =
                        String::from_utf8_lossy(payload).into_owned();
                }
                2 => {
                    if let Some(org) = parse_windsurf_org(payload) {
                        result.orgs.push(org);
                    }
                }
                3 => {
                    result.auth1_token =
                        Some(String::from_utf8_lossy(payload).into_owned());
                }
                4 => {
                    result.account_id =
                        Some(String::from_utf8_lossy(payload).into_owned());
                }
                5 => {
                    result.primary_org_id =
                        Some(String::from_utf8_lossy(payload).into_owned());
                }
                _ => {} // Unknown fields ignored
            }
            i = end;
        } else {
            // Other wire types not needed yet, skip in minimal way
            match wire_type {
                0 => {
                    // varint, skip
                    let (_, c) = decode_varint(bytes, i).ok_or_else(|| {
                        AppError::Parse("Failed to skip varint".to_string())
                    })?;
                    i += c;
                }
                1 => i += 8, // 64-bit
                5 => i += 4, // 32-bit
                _ => {
                    return Err(AppError::Parse(format!(
                        "WindsurfPostAuth response encountered unsupported wire_type {}",
                        wire_type
                    )));
                }
            }
        }
    }

    if result.session_token.is_empty() {
        return Err(AppError::Api(
            "WindsurfPostAuth response did not contain session_token".to_string(),
        ));
    }

    Ok(result)
}

/// Parse CheckUserLoginMethodResponse
///
/// Proto structure:
/// - field 1: redirect_url (string, wire_type=2)
/// - field 2: disallow_enterprise_user_login (bool → varint, wire_type=0)
/// - field 3: user_exists (bool)
/// - field 4: is_migrated (bool)
/// - field 5: has_password (bool)
///
/// Unknown fields are skipped by wire_type to ensure forward compatibility.
fn parse_check_user_login_method_response(
    bytes: &[u8],
) -> AppResult<CheckUserLoginMethodResult> {
    let mut result = CheckUserLoginMethodResult::default();
    let mut i = 0;

    while i < bytes.len() {
        let (tag, consumed) = decode_varint(bytes, i).ok_or_else(|| {
            AppError::Parse("Failed to decode CheckUserLoginMethod response tag varint".to_string())
        })?;
        i += consumed;

        let field_no = (tag >> 3) as u32;
        let wire_type = (tag & 0x7) as u8;

        match (field_no, wire_type) {
            (1, 2) => {
                let (len, cl) = decode_varint(bytes, i).ok_or_else(|| {
                    AppError::Parse(
                        "Failed to decode CheckUserLoginMethod redirect_url length varint".to_string(),
                    )
                })?;
                i += cl;
                let end = i + len as usize;
                if end > bytes.len() {
                    return Err(AppError::Parse(
                        "CheckUserLoginMethod redirect_url length out of bounds".to_string(),
                    ));
                }
                result.redirect_url = String::from_utf8_lossy(&bytes[i..end]).into_owned();
                i = end;
            }
            (2, 0) | (3, 0) | (4, 0) | (5, 0) => {
                let (v, c) = decode_varint(bytes, i).ok_or_else(|| {
                    AppError::Parse(format!(
                        "Failed to decode CheckUserLoginMethod field {} varint",
                        field_no
                    ))
                })?;
                i += c;
                match field_no {
                    2 => result.disallow_enterprise_user_login = v != 0,
                    3 => result.user_exists = v != 0,
                    4 => result.is_migrated = v != 0,
                    5 => result.has_password = v != 0,
                    _ => {}
                }
            }
            _ => {
                // Unknown fields skipped by wire_type to ensure forward compatibility
                match wire_type {
                    0 => {
                        let (_, c) = decode_varint(bytes, i).ok_or_else(|| {
                            AppError::Parse("Failed to skip varint".to_string())
                        })?;
                        i += c;
                    }
                    2 => {
                        let (len, cl) = decode_varint(bytes, i).ok_or_else(|| {
                            AppError::Parse("Failed to skip length-delimited".to_string())
                        })?;
                        i += cl + len as usize;
                    }
                    1 => i += 8,
                    5 => i += 4,
                    _ => {
                        return Err(AppError::Parse(format!(
                            "CheckUserLoginMethod unsupported wire_type {}",
                            wire_type
                        )));
                    }
                }
            }
        }
    }

    Ok(result)
}

/// Parse WindsurfPostAuthOrg sub-message (field 1=id, field 2=name)
fn parse_windsurf_org(bytes: &[u8]) -> Option<WindsurfOrg> {
    let mut org = WindsurfOrg::default();
    let mut i = 0;

    while i < bytes.len() {
        let (tag, consumed) = decode_varint(bytes, i)?;
        i += consumed;
        let field_no = (tag >> 3) as u32;
        let wire_type = (tag & 0x7) as u8;
        if wire_type != 2 {
            // Current structure only uses string fields, abort directly for other types
            return None;
        }
        let (len, consumed_len) = decode_varint(bytes, i)?;
        i += consumed_len;
        let end = i + len as usize;
        if end > bytes.len() {
            return None;
        }
        let payload = &bytes[i..end];
        match field_no {
            1 => org.id = String::from_utf8_lossy(payload).into_owned(),
            2 => org.name = String::from_utf8_lossy(payload).into_owned(),
            _ => {}
        }
        i = end;
    }

    if org.id.is_empty() && org.name.is_empty() {
        None
    } else {
        Some(org)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_varint_roundtrip() {
        let mut buf = Vec::new();
        encode_varint(&mut buf, 150);
        assert_eq!(buf, vec![0x96, 0x01]);

        let (v, consumed) = decode_varint(&buf, 0).unwrap();
        assert_eq!(v, 150);
        assert_eq!(consumed, 2);
    }

    #[test]
    fn test_string_field_encoding() {
        let mut buf = Vec::new();
        encode_proto_string_field(&mut buf, 1, "auth1_test");
        // tag = (1 << 3) | 2 = 10 = 0x0a
        assert_eq!(buf[0], 0x0a);
        // length = 10
        assert_eq!(buf[1], 10);
        assert_eq!(&buf[2..], b"auth1_test");
    }

    #[test]
    fn test_parse_har_auth1_token_field_encoding() {
        // Reproduce body captured in HAR: "\n:auth1_4phbs32swt5f66xsq26dr4eiziz6ahm3cj6n3ehd7mx6huj4zy5a"
        let auth1_token = "auth1_4phbs32swt5f66xsq26dr4eiziz6ahm3cj6n3ehd7mx6huj4zy5a";
        let mut buf = Vec::new();
        encode_proto_string_field(&mut buf, 1, auth1_token);
        assert_eq!(buf[0], 0x0a, "field 1 tag");
        assert_eq!(buf[1], 0x3a, "length=58 (':' = 0x3A)");
        assert_eq!(&buf[2..], auth1_token.as_bytes());
    }
}
